services:
  uwb_localization:
    build:
      context: ..
      dockerfile: Dockerfile
      target: release
    image: "mapcore.jfrog.io/robotics/uwb_localization/v0.0.4"
    user: ros
    working_dir: /workspaces/uwb_localization
    command: >
      bash -lc '
        set -e;
        source /opt/ros/humble/setup.bash;
        colcon build --symlink-install --packages-select uwb_viz uwb_serial_pub;
        source install/setup.bash;
        RVIZ_CFG="$(ros2 pkg prefix uwb_serial_pub)/share/uwb_serial_pub/rviz/multi_anchor_circles.rviz";
        ros2 launch uwb_viz static_tf.launch.py config:=/workspaces/uwb_localization/config/anchors.yaml rviz_config:=$RVIZ_CFG &
        ros2 launch uwb_serial_pub uwb_pf.launch.py params_file:=/workspaces/uwb_localization/config/uwb_pf_params.yaml use_robot_state_publisher:=true &
        wait -n
      '
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    ipc: host
    volumes:
      - "..:/workspaces/uwb_localization"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/dev:/dev"
    environment:
      - "DISPLAY=${DISPLAY}"
      - "QT_X11_NO_MITSHM=1"
      - "QT_GRAPHICSSYSTEM=native"
      - "ROS_DOMAIN_ID=86"
